name: youtube_dl
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  youtube_explode_dart: ^1.10.4
  group_radio_button: ^1.3.0
  filesystem_picker: ^3.0.0
  path_provider: ^2.0.14
  youtube_api: ^1.0.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

